# Generated by Django 4.2.2 on 2023-07-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='birthdate',
            new_name='date_posted',
        ),
    ]
